### PR TITLE
Update to use ansi-html-community

### PR DESCRIPTION
**Pull request by ljones92**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

Update to ansi-html-community package in place of ansi-html which is no longer maintained. This is to address the following CVE - https://github.com/advisories/GHSA-whgm-jr23-g3j9

### CODE REVIEW

**Comment by Andrii-Zarin** [comment]
Hi, can you please approximately estimate when this pr will be mergerd and npm package @gatsbyjs/webpack-hot-middleware will be updated, cause ansi-html dependency produces audit error.

**Comment by davychhouk** [comment]
+1

**Comment by davychhouk** [comment]
@ljones92 You actually have to update this line, too.

In `client-overlay.js`: 

```
var ansiHTML = require('ansi-html'); <--- Replace with ansi-html-community
```

**Comment by dictyo** [comment]
+1

**Comment by karlhorky** [comment]
@wardpeet would you accept this PR? Or should it just bump the version of `ansi-html` (without switching to the other `ansi-html-community` package)?

**Comment by wardpeet** [comment]
Published in v.2.25.3

**Pull request merged**
